stages:
  - build
  - test

build-arch:
  stage: build
  image: archlinux:base
  needs: []
  before_script:
    - "pacman -Syu --noconfirm"
    - "pacman -S --needed --noconfirm cargo base-devel"
  script:
    - "cargo build"
    - "cargo build --release"
  artifacts:
    paths:
      - target/debug/ripcalc
      - target/release/ripcalc

build-ubuntu-trusty:
  stage: build
  image: ubuntu:trusty
  needs: []
  before_script:
    - "apt -y update"
    - "export LANG=C.UTF-8"
    - "export LC_ALL=C.UTF-8"
    - "apt -y install curl build-essential"
    - "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
    - "source $HOME/.cargo/env"
  script:
    - "cargo build"
    - "cargo build --release"
  artifacts:
    paths:
      - target/debug/ripcalc
      - target/release/ripcalc

build-ubuntu-focal:
  stage: build
  image: ubuntu:focal
  needs: []
  before_script:
    - "apt -y update"
    - "export LANG=C.UTF-8"
    - "export LC_ALL=C.UTF-8"
    - "apt -y install curl build-essential"
    - "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
    - "source $HOME/.cargo/env"
  script:
    - "cargo build"
    - "cargo build --release"
  artifacts:
    paths:
      - target/debug/ripcalc
      - target/release/ripcalc

test:
  stage: test
  image: archlinux:base
  needs:
    - job: build-arch
      artifacts: true
  before_script:
    - "pacman -Syu --noconfirm"
    - "pacman -S --needed --noconfirm cargo base-devel"
  script:
    - "cargo test"
